### ISSUE TITLE
UI elements are broken when navigated with "Tab" button

### ISSUE THREAD

**Issue by mike1808** [pivotal-cf/pairist#12]
Try to press Tab button several times and UI elements will move to different directions

![Screen Shot 2019-08-30 at 11 46 00 AM](https://user-images.githubusercontent.com/3942554/64044478-c0c1e980-cb1b-11e9-9ee6-1b5f185efcc9.png)

**Comment by luan** [comment]
Can confirm, we should definitely look into this! Thanks @mike1808

**Comment by reidmit** [comment]
I'm going to close this, since the v2 rewrite has now been released and this bug is not present there. Please file a new issue for any new bugs you notice in v2!
