### ISSUE TITLE
If the recommendation is the same as the current arrangement, pair.ist does not record history

### ISSUE THREAD

**Issue by jaresty** [pivotal-cf/pairist#15]
When you click "recommend", if the pairing is already "optimal" then pair.ist will not record a new history entry. Since history drives the pairing recommendations, this situation causes a recurring problem since the next day it will do the same thing.

**Comment by jaresty** [comment]
TLDR; There is a background task that is kicked off when the pairing changes.  If the pairing doesn't change when clicking "recommend", then I suspect that task would not be kicked off which could be causing this issue.

**Comment by reidmit** [comment]
I'm going to close this, since the v2 rewrite has now been released and this bug is not present there. Please file a new issue for any new bugs you notice in v2!
