### ISSUE TITLE
[feature request] CLI

### ISSUE THREAD

**Issue by a-b** [pivotal-cf/pairist#18]
It would be great to be able to push helps and interesting via the CLI client.

**Comment by reidmit** [comment]
Thanks for the feature request! I agree this would be very cool. Although I haven't had a lot of time to work on Pair.ist lately, I've been thinking about what a "Pair.ist 2.0" might look like in the back of my mind. One idea was a simple, well-documented API that could be used for retrieving current pairs/tracks. I could also imagine the API letting you read/update lists (like helps and interestings). And then a CLI could be built on top of that.

I will keep this open as a good idea to think about going forward!

**Comment by a-b** [comment]
You're right, well-documented API would do the trick!

**Comment by reidmit** [comment]
After thinking more about this, I still think it would be cool, but I feel it's out of scope for the Pairist project itself. I recommend that you take a look at the [go-pairist](https://github.com/dpb587/go-pairist) library, an unofficial Go client library that makes it easier to interact with Pairist programmatically. There is also a very simple CLI in that project – would be a good reference point for people wanting to build something more complex.

You might also be interested in [this PR](https://github.com/dpb587/go-pairist/pull/4), which updates go-pairist for Pairist 2, and in [this doc](https://github.com/pivotal-cf/pairist/blob/v2/docs/api.md), which describes how to consume the Pairist API.
