### ISSUE TITLE
[feature request] Clickable links in list items

### ISSUE THREAD

**Issue by rainmaker** [pivotal-cf/pairist#4]
Hi pairist friends,

Our team has started to use pairist for our standup board, and might use it for tech forum in the future. One nice-to-have for lists would be clickable links.

![screenshot](https://i.imgur.com/UV6as76.png)

At the moment, I have to select and copy any link I want to follow. It would be even COOLER if I could use markdown to format a link, but now I'm just asking for things I don't really need :D

Thanks, and let me know if you have any questions.

Raina

**Comment by reid47** [comment]
It looks like this is possible with the newly-added Markdown support. Markdown links are rendered as clickable.

**Comment by reidmit** [comment]
I'm going to close this now, since clickable Markdown links have been supported for a while. Thank you!
