### ISSUE TITLE
Bugfix: Days of the week in history are misleading

### ISSUE THREAD

**Issue by tjvman** [pivotal-cf/pairist#5]
In the history sidebar, days of the week appear as follows (for this example, assume that "Today" is a Wednesday):
`11/27, Last Friday, Last Monday, Tuesday, Wednesday, Thursday, Friday, Monday, Yesterday, Current`

This is confusing because it lists days from the previous week as though they were days from the current week. A more straightforward ordering (IMO) would be: 
`11/27, 11/28, Last Monday, Last Tuesday, Last Wednesday, Last Thursday, Last Friday, Monday, Yesterday, Current`

So, today is listed as `Current`
Previous day is `Yesterday`
All other days in the current week are listed by their day names
Days in the previous week are listed by day name, prefixed with `Last`
Days from 2 or more weeks ago are listed in MM/DD format.

**Comment by reidmit** [comment]
I'm going to close this, since the v2 rewrite has now been released and this bug is not present there. Please file a new issue for any new bugs you notice in v2!
