### ISSUE TITLE
List deletion auto-confirmed when using keyboard navigation

### ISSUE THREAD

**Issue by reid47** [pivotal-cf/pairist#8]
When using keyboard navigation (tab + enter), the behavior is strange when deleting lists. 

**To reproduce:**

1. Create a new list in the sidebar (with or without keyboard navigation)
2. Use tab to navigate to the delete button for this list
3. Use enter to press the delete button

**Expected:**

The confirmation modal pops up and allows me to either confirm or cancel the deletion.

**Actual:**

The confirmation modal pops up, but it immediately confirms the deletion and closes (without giving me time to cancel).

It works as expected when using the mouse to click.

**EDIT:**

It appears this behavior affects all modals (like when adding a new person). However, it is most problematic for deletions, since it doesn't give you a chance to cancel. When adding a new person, the modal just closes immediately without doing anything.

**Comment by reid47** [comment]
I'd be interested in digging into this and submitting a PR with a fix, if that's okay.

**Comment by luan** [comment]
Absolutely! Go ahead. Let me know if you need any help with context on
things.

**Comment by reidmit** [comment]
I'm going to close this, since the v2 rewrite has now been released and this bug is not present there. Please file a new issue for any new bugs you notice in v2!
