### ISSUE TITLE
Console error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by reid47** [pivotal-cf/pairist#9]
When visiting the app, you get an error like this in the console:

```
TypeError: Cannot read property 'length' of undefined
    at s.fontSize (Person.vue:62)
    ...
```

I did some investigating and found the cause, but not sure yet of the best way to fix it. The line causing the problem looks like: 

```
if (this.person.name.length < 8) {
```

There's a person in the database without a `name` field. I believe this is the person that gets created by default when you make a new team. You can confirm this by looking at the responses we get back from Firebase. One of the `entities` looks like this:

```
{location: "unassigned", type: "person", updatedAt: 1561408519345}
```

I can think of a couple paths forward, but wanted to ask some questions.

It would be straightforward to just filter out `entities` without a `name` set before we try to render any of them. But is the real problem that this person gets created at all, or maybe that it gets created without an `name`? If we do want that original person to show up in the list of "People," what name should it have by default?

I'm happy to try to fix this in whatever way you think is best.

**Comment by luan** [comment]
I ended up fixing this by allowing persons to be shown without a name, sorry I didn't reply to this earlier to help you get tot a fix.
